language: node_js
node_js:
- '6'
before_script:
 npm install -g jasmine
deploy:
  provider: heroku
  api_key:
    secure: Kzm3Xchlyxb0NpFGwfCet5sM6WoCFAIQIX+7ATJdPdNX/FlaNcBz7jJXca7n+P02QF1rVq25yJ3w4Tj73NBtUXVmoPY8yHZCdaJfoLE6qxv2EkaKhqLNjb4Z3B6s7bulk+FRAft5wcS0pkOpT2SOfIosboRdRgTnGxc8WetYdUdaG/ivC0zDcAuRDMQ2wU0sq9V4WMT/vp7oEVrpBWqyLC/qjvJ6mX6Xydjb36Ime9K1YKmfT6sRraY/CFO9SCuqu83hrp5cIhnRu+E2fmVddFUMh+lo8j+qkfK2MrCPUezI+3zjBeMBcQGhQjgjEDDq7Hlv1Kjadk5PNeQRWLOCEU1b9l+6l6p1Sknc7vaBdr3Z7CU714X2B4wUvKuN1qOv0Wf+xpRlUaJEOBVTeoJosw8QxITCrDdK5P8z5P4neVAXGqCJ8Q9F/BmrsRartqWNuIEU/PMl5ObXEJMqSUs1u9is97pfO68bKYK7/kOrU2BJ3gnAOX1wMjYoX7Isn2l8Q2lS6UztK9ddKu/e1Ms0eEPnjsoX+RA01CRCxLWwqgHLIrzM5ptO5rHC4S5z2uHSdFu+Sxkn1IwPtmuFJgSTNEduKNLOjfeb1NVAI5E/R0I1TxmWKO3mOjOHsGGQQ/zTZLjqLf0wnmYRyKhiM5er1hZaqLhPPJ12vfFcRR+i/hw=
  app: powerful-basin-35042
notifications:
  slack:
    secure: Nk2OEYdh4Z4BYYh5jvM0vbavSuRKTpnBXwPXyZCuJMbEMK2YQF3OK6MA2FvtErdSFLAxfnx2P50jteYyby/IjddwQL2/2Q96+a9DoSmowvyIL1o/z3FLjLQ3KfPX0KmATG87FPgjd4kndtcehE0NNO0NGSB18zkUxF9nRLgQKc/6sEGgrYBxHNKV7nJyQCqwIrfA4hPGfenXEPkKxUyIJYM42m0nD/abcNw0R4EutEJWDKXHmfBN3wFQTMosZmS7vezAiMMdMGEd5ML2RM1PprL0zmiMD5uFsae0IaBtK7S35dcm1hik8ZA1dKsn2AHYDbO46ZJafEaw0DIjarAQ3Gxei4btDBZn2mx79lFHJnhtXzM9jZdDe2lokg/0p3HG5EqLzQKWYAy9yJBgpHJhPsQfRPgkzIj9GSBhJ254V1rq+YIU/M6wwZunIKDTfzEPGCDw9Y82+o735QI14euIqUka/etOSwknx9VtctYDkBGpAoE1RIxANdnIg8B46W7/W+gGuD/hcHeG+RRppGm/+KSZI+lcfe6eD89EqK8sOSluP2C66rP1bI7jcG0elWTMfj3RubezYurzvr9dNKamUvgDgRg/qFM7OJeMB2wS6WOAS1/mCV99TFHE+os5qurnSOHvqmN3tY4APoU3GygO7KmMDzQEb0seEAHQgGpzg+0=
addons:
  sonarqube:
    token:
      secure: "iv8kS4nls2dTW6uF5oLOvq1l9bKCrXqNOa+K//3Q7sOnlvjJLbabH/JhD0Ez6mFyCxxAsXooLV9WpV8+koiffXHVCuzwFu5W8vs98pxrEwBnP/UK9cQ5m8PTjNUY/c4hdNRzH/i8f4d9V3jc8WAJOEfGmaoRHT+jneR6YDxsVv+Gzu6kpqCBX+kJ14+6qgNfMES+oaBioqh5A9wGHIptBwBcSUCpGeQeyF28W+JpPhhvtr0HJ9ng6ORud9OQe2Jc9YLT5+qCrKvWamaWDKCJXPdU59BJhbhYBZ7KKqz1JrTJaS2/6eOaZFkmysHI6mYUmEhnD6uFs9ShhukZCDDSLX56153OxI5epL7aZfB2zdtJEXFl+yfVgM0Un3/9t5c8eNhUBo3OtNE5M9VQd9TznWAh3eXOJaljgaE7wjXUQBTTlPZdOlvhXuUvVA6Xer5SoI8tLdlTjk2lBP1ssKaojjAjJQ4kQMxNPKDDCzkcsEy9m/8juz8hJr/GhHGswXLZEtgWrcaaDKTJGgM4rUQjXz2cGCV4T5MHoy1yVnd0fm7AniIwHM42FJQDuVC5r03BsTJkSp+F39e2UFi1LF6p87Ebf9GXxv6vIi8gBmrxMJ1cu46r3Q0rdkdRitfWGv6ZBrLAEbw3G/p0D5oOXxoKdLxxkqQ9b2sQ5UASOVGY03A="
  branches:
    - master
  script:
    - sonar-scanner